dist: xenial

language: python

# cache:
#   directories:
#   - /home/travis/download
#   - /home/travis/.cache/pip

# This matrix tests that the code works on Python 3.5, 3.6, and passes lint.
matrix:
  fast_finish: true
  include:
    - env: PYTHON_VERSION="3.5" COVERAGE="true"
    - env: PYTHON_VERSION="3.6" COVERAGE="true"
    - env: PYTHON_VERSION="3.5" RUN_FLAKE8="true" SKIP_TESTS="true"

addons:
  apt:
    packages:
      sox
      libsox-dev
      libsox-fmt-all

notifications:
  email: false

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh

branches:
  only:
    - master
    - travis
