channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - numpy
  - pytest
  - pytest-cov
  - codecov
  - librosa
  - pip
  - pip:
    - clang-format
    - kaldi-io
    - scipy
    - parameterized
    - numba==0.48
