# a comment for these trying times
channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - numpy >= 1.11
  - pytest
  - pytest-cov
  - codecov
  - librosa >= 0.8.0
  - llvmlite==0.31  # See https://github.com/pytorch/audio/pull/766
  - pip
  - pip:
    - clang-format
    - kaldi-io
    - scipy
    - parameterized
