channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - numpy
  - pytest
  - pytest-cov
  - codecov
  - scipy >= 1.4.1
  - pip
  - pip:
    - kaldi-io
    - PySoundFile
    - future
    - parameterized
    - dataclasses
