channels:
  - conda-forge
  - defaults
dependencies:
  - flake8
  - numpy
  - pytest
  - pytest-cov
  - codecov
  - librosa #[not win]
  - pip
  - pip:
    - kaldi-io
    - scipy
    - PySoundFile
    - librosa #[win]
