name: Trigger Linux Conda Build for Nightlies/Release

on:
  pull_request:
    paths:
      - .github/workflows/build_conda_linux.yml
  push:
    branches:
      - nightly
  workflow_dispatch:

jobs:
  generate-matrix:
    uses: pytorch/test-infra/.github/workflows/generate_binary_build_matrix.yml@main
    with:
      package-type: conda
      os: linux
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
  build:
    needs: generate-matrix
    strategy:
      fail-fast: false
      matrix:
        include:
          - repository: pytorch/audio
            pre-script: packaging/pre_build_script.sh
            post-script: packaging/post_build_script.sh
            package-name: torchaudio
    name: ${{ matrix.repository }}
    uses: pytorch/test-infra/.github/workflows/build_conda_linux.yml@main
    with:
      conda-package-directory: packaging/torchaudio
      repository: ${{ matrix.repository }}
      ref: nightly
      test-infra-repository: pytorch/test-infra
      test-infra-ref: main
      build-matrix: ${{ needs.generate-matrix.outputs.matrix }}
      pre-script: ${{ matrix.pre-script }}
      post-script: ${{ matrix.post-script }}
      package-name: ${{ matrix.package-name }}
      # Using "development" as trigger event so these binaries are not uploaded
      # to official channels yet
      trigger-event: development
    secrets:
      CONDA_PYTORCHBOT_TOKEN: ${{ secrets.CONDA_PYTORCHBOT_TOKEN }}
      AWS_PYTORCH_UPLOADER_ACCESS_KEY_ID: ${{ secrets.AWS_PYTORCH_UPLOADER_ACCESS_KEY_ID }}
      AWS_PYTORCH_UPLOADER_SECRET_ACCESS_KEY: ${{ secrets.AWS_PYTORCH_UPLOADER_SECRET_ACCESS_KEY }}
