name: Build TorchAudio Linux Wheels

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-reusable-build-workflow:
    uses: pytorch/test-infra/.github/workflows/build_wheels_linux_reusable.yml@nirav_reusable_wf_script
    with:
      domain: "audio"
      image: "pytorch/manylinux-cuda113"